from django.db import models
from auth_app.models import User
import uuid

class Document(models.Model):
    """
    Represents a document uploaded by a user (student or faculty).
    """
    VERIFICATION_STATUS = [
        ('Pending', 'Pending'),
        ('Verified', 'Verified'),
        ('Rejected', 'Rejected'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='documents')
    document_type = models.CharField(max_length=100)
    file = models.FileField(upload_to='user_documents/')
    uploaded_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=20, choices=VERIFICATION_STATUS, default='Pending')

    def __str__(self):
        return f"{self.document_type} for {self.user.username}"

class Certificate(models.Model):
    """
    Represents an official certificate generated by the college.
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='certificates')
    certificate_type = models.CharField(max_length=100)
    issued_on = models.DateField(auto_now_add=True)
    verification_code = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    file = models.FileField(upload_to='generated_certificates/')

    def __str__(self):
        return f"{self.certificate_type} for {self.user.username}"
