# Generated by Django 5.2.7 on 2025-11-05 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0002_application_remove_meritlist_department_and_more"),
        ("students", "0002_student_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="department",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="students.department",
            ),
        ),
    ]
