# Generated by Django 5.2.8 on 2025-11-06 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0002_application_remove_meritlist_department_and_more"),
        ("workflow", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="status",
        ),
        migrations.AddField(
            model_name="application",
            name="current_stage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applications",
                to="workflow.stage",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="workflow",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applications",
                to="workflow.workflow",
            ),
        ),
    ]
