# Generated by Django 5.2.7 on 2025-11-04 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("faculty", "0002_faculty_user"),
        ("students", "0002_student_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(max_length=100)),
                ("quantity", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_id",
                    models.CharField(
                        help_text="Unique identifier for the asset (e.g., serial number, tag)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("purchase_date", models.DateField()),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("Good", "Good"),
                            ("Used", "Used"),
                            ("Damaged", "Damaged"),
                            ("Retired", "Retired"),
                        ],
                        default="New",
                        max_length=50,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "assigned_to_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="students.department",
                    ),
                ),
                (
                    "assigned_to_faculty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="faculty.faculty",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="inventory.inventoryitem",
                    ),
                ),
            ],
        ),
    ]
