# Generated by Django 5.2.8 on 2025-11-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stage",
            name="is_final",
            field=models.BooleanField(default=False),
        ),
    ]
