# Generated by Django 5.2.7 on 2025-11-05 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
        ("students", "0002_student_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="students.department",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("present", "Present"),
                    ("absent", "Absent"),
                    ("leave", "Leave"),
                ],
                max_length=10,
            ),
        ),
    ]
